### ISSUE TITLE
Deploy on cluster and test workflows

### ISSUE THREAD

**Issue by hopeyen** [graphops/subfile-data-service#61]
**Expectation proposal**

Support deployment on our cluster and test free query workflows
the file server should be 
- plugged into a s3 bucket
- use CLI to publish files and bundles and add to the file server
- expose service port 
- set a free query auth token

test with a different client  
- query status of the file server
- download some bundles with free query auth token

**Comment by cjorge-graphops** [comment]
Closing, no longer relevant
